/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package avast;

import java.awt.Color;

/**
 *
 * @author lahcen ait sidi ali
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        status = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        scan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tools = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        store = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        device = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        support = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        statistics = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        settings = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        other = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        bar = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        quick = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        clean = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        mobile = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(56, 56, 56));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(31, 31, 31));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        status.setBackground(new java.awt.Color(31, 31, 31));
        status.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        status.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/001.png"))); // NOI18N
        status.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 30, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 151, 0));
        jLabel2.setText("Status");
        status.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 20, 70, 20));

        menu.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 132, 60));

        scan.setBackground(new java.awt.Color(40, 40, 40));
        scan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        scan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                scanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                scanMouseExited(evt);
            }
        });
        scan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/002.png"))); // NOI18N
        scan.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 30, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(190, 190, 190));
        jLabel4.setText("Scan");
        scan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 20, 70, 20));

        menu.add(scan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 132, 60));

        tools.setBackground(new java.awt.Color(40, 40, 40));
        tools.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tools.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                toolsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                toolsMouseExited(evt);
            }
        });
        tools.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/003.png"))); // NOI18N
        tools.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 30, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(190, 190, 190));
        jLabel6.setText("Tools");
        tools.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 20, 70, 20));

        menu.add(tools, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 124, 132, 60));

        store.setBackground(new java.awt.Color(40, 40, 40));
        store.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        store.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                storeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                storeMouseExited(evt);
            }
        });
        store.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/004.png"))); // NOI18N
        store.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 30, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(190, 190, 190));
        jLabel8.setText("Store");
        store.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 20, 70, 20));

        menu.add(store, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 186, 132, 60));

        device.setBackground(new java.awt.Color(40, 40, 40));
        device.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        device.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deviceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deviceMouseExited(evt);
            }
        });
        device.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/005.png"))); // NOI18N
        device.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 30, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(190, 190, 190));
        jLabel10.setText("My devices");
        device.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 20, 70, 20));

        menu.add(device, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 248, 132, 60));

        support.setBackground(new java.awt.Color(40, 40, 40));
        support.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        support.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supportMouseExited(evt);
            }
        });
        support.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/006.png"))); // NOI18N
        support.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 30, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(190, 190, 190));
        jLabel12.setText("Support");
        support.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 20, 70, 20));

        menu.add(support, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 132, 60));

        statistics.setBackground(new java.awt.Color(40, 40, 40));
        statistics.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statistics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                statisticsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                statisticsMouseExited(evt);
            }
        });
        statistics.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/007.png"))); // NOI18N
        statistics.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 30, 30));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(190, 190, 190));
        jLabel14.setText("Statistics");
        statistics.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 20, 70, 20));

        menu.add(statistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 372, 132, 60));

        settings.setBackground(new java.awt.Color(40, 40, 40));
        settings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsMouseExited(evt);
            }
        });
        settings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/008.png"))); // NOI18N
        settings.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 30, 30));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(190, 190, 190));
        jLabel16.setText("Settings");
        settings.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 20, 70, 20));

        menu.add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 434, 132, 60));

        other.setBackground(new java.awt.Color(40, 40, 40));
        other.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        other.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/009.png"))); // NOI18N
        other.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 30, 30));

        menu.add(other, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 496, 132, 60));

        background.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 132, 550));

        bar.setBackground(new java.awt.Color(40, 40, 40));
        bar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        bar.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 105, 40));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("INTERNET SECURITY");
        bar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 210, 20));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("BETA");
        bar.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 20, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        bar.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 10, 25, 25));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reduire.png"))); // NOI18N
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        bar.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 10, 25, 25));

        jLabel22.setBackground(new java.awt.Color(107, 166, 16));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("BUY NOW");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204)));
        jLabel22.setOpaque(true);
        bar.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 20, 85, 20));

        background.add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 0, 690, 60));

        header.setBackground(new java.awt.Color(0, 167, 209));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        header.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 40, 53, 46));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Everything is good");
        header.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 48, -1, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Everything up-to-date");
        header.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 130, 15));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Firewall active");
        header.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 125, 130, 15));

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("All shields active");
        header.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 130, 15));

        jLabel28.setBackground(new java.awt.Color(254, 227, 0));
        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("In trial mode (29 days remaining)");
        jLabel28.setOpaque(true);
        header.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 0, 445, 30));

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 60, 690, 180));

        content.setBackground(new java.awt.Color(56, 56, 56));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quick.setBackground(new java.awt.Color(39, 39, 39));
        quick.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 84, 84)));
        quick.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quick.png"))); // NOI18N
        quick.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 15, 45, 45));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(190, 190, 190));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Quick scan");
        quick.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 143, 15));

        content.add(quick, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 143, 98));

        clean.setBackground(new java.awt.Color(39, 39, 39));
        clean.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 84, 84)));
        clean.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clean.png"))); // NOI18N
        clean.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 15, 45, 45));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(190, 190, 190));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Mobile protection");
        clean.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 143, 15));

        content.add(clean, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 143, 98));

        add.setBackground(new java.awt.Color(56, 56, 56));
        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 84, 84)));
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        add.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 15, 45, 45));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(84, 84, 84));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Add");
        add.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 143, 15));

        content.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 143, 98));

        mobile.setBackground(new java.awt.Color(39, 39, 39));
        mobile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 84, 84)));
        mobile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mobile.png"))); // NOI18N
        mobile.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 15, 45, 45));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(190, 190, 190));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Mobile protection");
        mobile.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 143, 15));

        content.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 30, 143, 98));

        jPanel1.setBackground(new java.awt.Color(56, 56, 56));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 84, 84)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(190, 190, 190));
        jLabel37.setText("<html>\n<head>\n<style>\nspan{\n  font-weight: bold;\n}\n</style>\n</head>\n<body>\n<p>Try our <span>SecureLine VPN</span> service. It's part of the avast!</p>\n</body>\n</html>");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 420, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok2.png"))); // NOI18N
        jLabel38.setText("jLabel38");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 12, 12));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(148, 148, 148));
        jLabel39.setText("Safety on public WiFi");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 270, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok2.png"))); // NOI18N
        jLabel40.setText("jLabel38");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 12, 12));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(148, 148, 148));
        jLabel41.setText("All access to content from anywhere");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 270, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(148, 148, 148));
        jLabel42.setText("Anonymous surfing");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 270, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok2.png"))); // NOI18N
        jLabel43.setText("jLabel38");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 12, 12));

        jLabel44.setBackground(new java.awt.Color(0, 166, 208));
        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Try now");
        jLabel44.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel44.setOpaque(true);
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel44MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel44MouseExited(evt);
            }
        });
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 85, 132, 39));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img.png"))); // NOI18N
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 100));

        content.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 648, 140));

        background.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 240, 690, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void scanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scanMouseEntered
        scan.setBackground(Color.decode("#1f1f1f"));
    }//GEN-LAST:event_scanMouseEntered

    private void scanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scanMouseExited
        scan.setBackground(Color.decode("#282828"));
    }//GEN-LAST:event_scanMouseExited

    private void toolsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolsMouseEntered
        tools.setBackground(Color.decode("#1f1f1f"));
    }//GEN-LAST:event_toolsMouseEntered

    private void toolsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolsMouseExited
        tools.setBackground(Color.decode("#282828"));
    }//GEN-LAST:event_toolsMouseExited

    private void storeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storeMouseEntered
        store.setBackground(Color.decode("#1f1f1f"));
    }//GEN-LAST:event_storeMouseEntered

    private void storeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storeMouseExited
        store.setBackground(Color.decode("#282828"));
    }//GEN-LAST:event_storeMouseExited

    private void deviceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceMouseEntered
        device.setBackground(Color.decode("#1f1f1f"));
    }//GEN-LAST:event_deviceMouseEntered

    private void deviceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceMouseExited
        device.setBackground(Color.decode("#282828"));
    }//GEN-LAST:event_deviceMouseExited

    private void supportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supportMouseEntered
        support.setBackground(Color.decode("#1f1f1f"));
    }//GEN-LAST:event_supportMouseEntered

    private void supportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supportMouseExited
        support.setBackground(Color.decode("#282828"));
    }//GEN-LAST:event_supportMouseExited

    private void statisticsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statisticsMouseEntered
        statistics.setBackground(Color.decode("#1f1f1f"));
    }//GEN-LAST:event_statisticsMouseEntered

    private void statisticsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statisticsMouseExited
        statistics.setBackground(Color.decode("#282828"));
    }//GEN-LAST:event_statisticsMouseExited

    private void settingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseEntered
        settings.setBackground(Color.decode("#1f1f1f"));
    }//GEN-LAST:event_settingsMouseEntered

    private void settingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseExited
        settings.setBackground(Color.decode("#282828"));
    }//GEN-LAST:event_settingsMouseExited

    private void jLabel44MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseEntered
        jLabel44.setBackground(Color.decode("#02b6e3"));
    }//GEN-LAST:event_jLabel44MouseEntered

    private void jLabel44MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseExited
        jLabel44.setBackground(Color.decode("#00a6d0"));
    }//GEN-LAST:event_jLabel44MouseExited

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel21MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add;
    private javax.swing.JPanel background;
    private javax.swing.JPanel bar;
    private javax.swing.JPanel clean;
    private javax.swing.JPanel content;
    private javax.swing.JPanel device;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel mobile;
    private javax.swing.JPanel other;
    private javax.swing.JPanel quick;
    private javax.swing.JPanel scan;
    private javax.swing.JPanel settings;
    private javax.swing.JPanel statistics;
    private javax.swing.JPanel status;
    private javax.swing.JPanel store;
    private javax.swing.JPanel support;
    private javax.swing.JPanel tools;
    // End of variables declaration//GEN-END:variables
}
